### PR TITLE
Swift 2.3 Support

### PR DESCRIPTION
**Pull request by dbburgess**
This likely isn't ready to merge as-is~~, especially given the awkward way it depends on the [`Alamofire/Alamofire:swift2.3`](https://github.com/Alamofire/Alamofire/tree/swift2.3) branch (they've yet to publish a release officially supporting it)~~.

99% of the diff is just dependency updates to pull in proper 2.3 support in all of the dependencies. The other 1% were simply recommend project setting changes that Xcode 8 Beta 6 suggested, and a few minor (but potentially dubious) code changes to support 2.3. At this point, it's also relatively untested.

I primarily put this up so anyone else who may be looking at using 2.3 might have a reference / fork to use. Ultimately, it'd be nice to clean this up ~~(hopefully with Alamofire officially providing a 2.3 release)~~ to ensure this plays nicely and doesn't break things for people running 2.2, but I'm not sure how feasible that is.

### CODE REVIEW

**Comment by romk1n** [comment]
@dbburgess can this be udpated , alamofire release 3.5.0 which should work for both i think ?

**Comment by dbburgess** [comment]
@romk1n Sure, no problem. I've updated it to use [Alamofire 3.5.0](https://github.com/Alamofire/Alamofire/releases/tag/3.5.0).

**Comment by AnthonyMDev** [comment]
@dbburgess Thanks for this. I'll get this merged shortly!

**Comment by romk1n** [comment]
@dbburgess awesome, probably need to update `travis.yaml` file to use xcode 8 to pass the build :)

**Comment by dbburgess** [comment]
Huzzah! There we go. It took a bit of putzing around to get the config correct, but that seems to have done it.

**Comment by AnthonyMDev** [comment]
Thanks for this! It's been merged into a `swift-2.3` branch.

**Comment by romk1n** [comment]
@AnthonyMDev @dbburgess hey guys with swift 2.3 i am still getting those errors in xcode 8, any ideas ? 

```
Pods/AmazonS3RequestManager/Source/AmazonS3ACL.swift:41:36: error: 'inout' must appear before the parameter name
    func setACLHeaders(on request: inout NSMutableURLRequest)
                                   ^~~~~~
                       inout       
```

**Comment by dbburgess** [comment]
@romk1n That line in the [`swift-2.3`](https://github.com/AnthonyMDev/AmazonS3RequestManager/blob/swift-2.3/Source/AmazonS3ACL.swift#L41) branch is:

``` swift
func setACLHeaders(inout forRequest request: NSMutableURLRequest)
```

The `inout` parameter comes _before_ the parameter name in Swift 2. That changed in Swift 3, where `inout` comes before the _type_. From the [`swift-3`](https://github.com/AnthonyMDev/AmazonS3RequestManager/blob/swift-3/Source/AmazonS3ACL.swift#L41) branch:

``` swift
func setACLHeaders(on request: inout NSMutableURLRequest)
```

...So, either you've got the wrong branch, or the Xcode conversion tool got ran on the code. :)

**Comment by romk1n** [comment]
@dbburgess hmm, interesting, maybe i should just try and use swift-2.3 branch instead

**Pull request merged**
