### PR TITLE
Fixes #18 problem with bucket listing

### LINKED ISSUE #18: Listing buckets not possible due to leading slash
When trying to list a bucket using `manager.amazonURLRequest(.GET, path : "")` the request fails because the S3 REST API doesn't accept a leading slash.

### PR DESCRIPTION
**Pull request by sebromero**
Allows to list buckets while maintaining API compatibility.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
@sbhklr I made a minor refactor to this PR and pulled the changes into `/develop` while maintaining attribution to you for your changes. This will be released in the next version shortly.

Thanks so much for catching this. And kudos on making PRs that contain tests!

**Comment by sebromero** [comment]
Sure thing. The refactoring makes sense and probably merging PR into dev first makes even more sense :)

**Comment by AnthonyMDev** [comment]
Yeah, I always try to make my changes on `/development` first. :+1:

**Comment by AnthonyMDev** [comment]
FYI: `0.10.2` has been pushed with this included.

**Pull request closed without merging**
