### PR TITLE
Fixes #36

### LINKED ISSUE #36: S3ObjectMetaData initializer crashes
When fetching meta data for an S3 object the `S3ObjectMetaData` initializer crashes with a bad access exception. This is most likely due to the `representation` parameter that is of typ `Any`. This apparently leads to a memory problem because the representation object won't be retained until the end of the initializer.

### PR DESCRIPTION
**Pull request by sebromero**
Fixes the issue by using the proper parameter type.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
@sbhklr Thanks again for working on this one. 

Since we aren't actually using the `representation` in this object, I don't want to force the parameter to be an `XMLIndexer`. I understand that using `Any` causes the retain issue. What about using `AnyObject`? That seems like a happy medium where we keep it relatively flexible, but it should be retained since we are confirming that it is an object.

**Comment by AnthonyMDev** [comment]
Actually, wouldn't we be able to make the `representation` type `Any?`. 
Making it optional might stop the crashing without any other issues.
Let me run a few tests and see what I can do.

**Comment by sebromero** [comment]
`Any?` doesn't stop it from crashing and `AnyObject` leaves me with `S3Test/ViewController.swift:116:70: Cannot convert value of type '(Response<S3ObjectMetaData, NSError>) -> ()' to expected argument type 'Response<_, NSError> -> Void'` Hmm, not sure how to get rid of that 🤔

**Comment by AnthonyMDev** [comment]
Hmmm that's really odd. Can you send me an example project so I can see this bug for myself? Also, in #36 I mentioned changes I made in `develop`. Can you see if those changes fix this please.

**Comment by sebromero** [comment]
Sure. I'll try out your changes first.

**Comment by AnthonyMDev** [comment]
Looks like the other changes fixed. Closing this.

**Pull request closed without merging**
