### PR TITLE
Bucket content listing - Implements #28 and #6

### PR DESCRIPTION
**Pull request by sebromero**

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
This looks good so far.

We should also add the `continuationToken` to the bucket object like was done in da85913e3aa91dc4e852dc0d5dc7305e6cfa6a80.

I can merge this and then add that also later on.

I'll merge this with a few other changes later this evening.

**Comment by sharikov** [comment]
@sbhklr Nice! Thank you. 

One thing that might cause problems is encoding the continuation token with .URLQueryAllowedCharacterSet when it includes + characters. I had to use alphanumericCharacterSet in order for it to work properly.

**Comment by AnthonyMDev** [comment]
Thanks for noting that @sharikov 
@sbhklr, can we add a unit test for this situation please?

**Comment by sebromero** [comment]
Can anyone provide me with an example value of a `NextContinuationToken`?

**Comment by sebromero** [comment]
No worries, got one: `1/kCRyYIP+Apo2oop/Ga8/nVMR6hC7pDH/lL6JJrSZ3blAYaZkzJY/RVMcJ`

**Comment by sebromero** [comment]
I couldn't find any information about the encoding in the AWS docs. I guess `alphanumericCharacterSet` will do the trick. I'll update the code accordingly.

**Comment by sebromero** [comment]
@sharikov This should work now.

**Comment by sebromero** [comment]
@AnthonyMDev Regarding the stalling Travis builds: I'd suggest to switch from xctool to xcodebuild. This will most likely fix the issue.

**Comment by AnthonyMDev** [comment]
@sbhklr Thanks for the recommendation. I can look into that sometime this week.
But if you feel inclined, feel free to make a PR that edits the `.travis.yml` file and see if you can fix it!

**Comment by sharikov** [comment]
@sbhklr Thanks for changing that.

**Pull request merged**
