### PR TITLE
Bucket content listing - Implements #6 

### PR DESCRIPTION
**Pull request by sebromero**
Implements directory listing on S3 instances.
Example usage:

```
amazonS3Manager.listBucket().responseS3Object { (response: Response<S3ListBucketResult, NSError>) in
   if let files = response.result.value?.files {                
       for file in files {
           print(file.path)
       }
   }
}
```

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
@sbhklr Thanks so much for this! Great work. There are a few changes I think we should make here, but you've put in a huge amount of the leg work for me. I really appreciate it.
1. I'd like to make the `ResponseObjectSerializable` use an associated object for the `representation`.
2. Should `XMLResponseSerializer` be public? Generally, XML serialization is not really within the scope of the library, and I could see this having naming conflicts with other `Alamofire` extension libraries that focus on XML serialization. I think we should make this private and just use it within our public serializers.

Thought on these changes?

**Comment by AnthonyMDev** [comment]
I've created a new branch `pr/23` for making the changes here. I've started on some minor edits. I'll probably have time to finish this sometime later this week. If you want to continue to contribute to these changes, please make PRs to that branch. Otherwise, you've already done a huge amount of work for me to get this implemented, so I'm happy to finish it. Thanks!

**Comment by sebromero** [comment]
@AnthonyMDev Sure thing, I'm happy to contribute. Regarding your suggestions:
1. I'm not quite sure what you mean by using an associated object. I did the implementation according to https://github.com/Alamofire/Alamofire#generic-response-object-serialization. Do you want to store the representation object as a property in `ResponseObjectSerializable`? I think we don't need this data anymore after being serialized into a domain object.
2. Agree. Probably we shouldn't expose that until we really have a need to do so. In that sense `s3DataResponseSerializer` doesn't have to be public either, does it?

**Comment by sebromero** [comment]
@AnthonyMDev I added another commit to this branch. Can you pull that into `pr/23`? I will push changes into `pr/23` from now on.

**Comment by AnthonyMDev** [comment]
@sbhklr I've finished all of the changes I want to make to `pr/23` and I'm going to be pulling it into `develop` shortly.

I don't think we should be adding the prefix parameter by using the `subresource` property. This feels like a hack to me. 
To implement this, we should prepare for the addition of query parameters to these requests. We should also handle all of the other possible parameters for a GET Bucket (List Objects) request. I'll make a new issue that addresses this and we can add it ASAP.

**Comment by AnthonyMDev** [comment]
This is being closed in favor of #29. That PR maintains attribution for all of your commits @sbhklr. Thanks!

**Pull request closed without merging**
